version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_panel
    ports:
      - '5433:5432'
    volumes:
      - ./pgData:/var/lib/postgresql/data

volumes:
  pgData:
    driver: local
